const translations = {
  en: {
    mainText: "Let's discover the potential.",
    mainP: "Come to study abroad with Global.",
    about: "About us",
    vision:"Our Vision",
    mission:"Our Mission",
    aboutT:"Global Group has been providing expert consultancy services in education and international employment across Turkey and Europe since 2018. Since our establishment, we have helped thousands of individuals pursue their dream education and build successful careers abroad. Our goal is to empower students, young professionals, and job seekers to discover their potential and guide them on the right path toward their goals. With a broad network of institutions, trusted partners, and an experienced team of consultants, we offer personalized and strategic solutions tailored to each individual. At Global Group, we are more than just a consultancy firm — we aim to be your partner on this journey. From education planning to job placement, we support you every step of the way with transparency, trust, and professionalism.",
    visionT:"Our vision is to become a leading force in the sector across Turkey and Europe by helping individuals become globally competent, informed, and confident.",
    missionT:"Our mission is to guide our clients in making the right decisions and walking confidently toward a brighter future.",
    partner: "Partner",
    Universities: "Universities",
    residence:"Resdence procedures",
    apply:"APPLY",
    How: "How to apply?",
    HowH1: "1. If you want to study in Turkey, you can do it easily.",
    HowH2: "1. You need to click the button above named 'GLOBAL'.",
    HowH3: "2. Then fill out the form and click the 'Send' button.",
    HowH4: "3. Please WAIT. We will call you.",
    HowH5: "4. If we haven't called, you can send an email or SMS.",
    agencyName:"Name of your Agency if you have:",
    adresse:"Adresse: Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"All Universities",
    approvedUni:"Approved Universities",
    viza:"Viza procedures",
    aboutmainTextTV:"Tourist Visa",
    aboutmainTextIV:"Worker Visa",
    aboutmainTextTrV:"Transit Visa",
    aboutmainTextMV:"Family Visa",
    aboutmainTextVV:"VIP  Visa",
    aboutmainTextOV:"Student Visa",
    service:"Services",


    cost: "Prices:",
    locationI: "Location: Istanbul.",
    locationAn:"Location: Ankara",
    locationIz:"Location: Izmir",
    locationKon:"Location: Konya",
    locationAnt:"Location: Antalya",
    locationAk:"Location: Aksaray",
    locationE:"Location: Erzurum",
    locationEs:"Location:: Eskishehir",
    locationB:"Location: Bursa",
    locationYo:"Location: Yozgat",
    locationBo:"Location: Bolu",
    locationBil:"Location: Bilecik",
    locationCh:"Location: Chankiri",
    locationAd:"Location:  Adana",
    locationDi:"Location: Diyarbakir",
    locationDu:"Location: Duzce",
    locationKa:"Location: Kaysery",
    locationEl:"Location: Elazig",
    locationKo:"Location: Kojaeli",
    locationKar:"Location: Karabuk",
    locationSak:"Location: Sakarya",
    locationM:"Location: Manisa",
    locationMal:"Location: Malatya",
    locationMer:"Location: Mersin",
    locationAf:"Location: Afyon",
    locatonAy:"Location: Aydyn",
    locationBur:"Location: Burdur",
    locationKut:"Location: Kutahya",
    locationErz:"Location: Erzinjan",
    locationCor:"Location: Chorum",
    locationGaz:"Location: Gaziantep",
    locationTra:"Location: Trabzon",
    locationKas:"Location: Kastamonu",
    locationKyr:"Location: Kyrrykkale",
    locationKir:"Location: Kyrshehir",
    locationMus:"Location: Mush",
    locationMug:"Location: Mugla",
    locationNig:"Location: Nigde",
    locationOr:"Location: Ordu",
    locationSam:"Location: Samsun",
    locationDen:"Location: Denizli",
    locationRiz:"Location: Rize",
    locationSiv:"Location: Sivas",
    locationIsp:"Location: Isparta",
    locationTok:"Location: Tokat",
    locationEd:"Location: Edirne",
    locationUs:"Location: Ushak",
    locationVan:"Location: Van",
    locationZon:"Location: Zonguldak",
    locationAdy:"Location: Adyyaman",
    locationAgr:"Location: Agry",
    locationAma:"Location: Amasya",
    locationArd:"Location: Ardahan",
    locationArt:"Location: Artvin",
    locationBal:"Location: Balykesir",
    locationBay:"Location: Bayburt",
    locationBin:"Location: Bingol",
    locationBit:"Location: Bitlis",
    locationCha:"Location: Chanakkale",
    locationGir:"Location: Giresun",
    locationGum:"Location: Gumushhane",
    locationHak:"Location: Hakkari",
    locationIgd:"Location: Ygdyr",
    locationIsk:"Location: Iskenderun",
    locationKars:"Location: Kars",
    locationKah:"Location: Kahramanmarash",
    locationKara:"Location: Karaman",
    locationKyrk:"Location: Kyrklareli",
    locationKil:"Location: Kilis",
    locationNev:"Location: Nevshehir",
    locationOsm:"Location: Osmaniye",
    locationSii:"Location: Siirt",
    locationSin:"Location: Sinop",
    locationShi:"Location: Shirnak",
    locationTek:"Location: Tekirdag",
    locationTrab:"Location: Trabzon",
    locationTun:"Location: Tunjeli",
    locationYal:"Location: Yalova",
    locationAl:"Location: Alanya",
    locationTar:"Location: Tarsus",
    






    altinbas:"Altynbash university",
    atilim:"Atylym university.",
    acibadem:"Ajybadem university.",
    akdeniz:"Akdeniz university.",
    aksaray:"Aksaray university.",
    ankara:"Ankara university.",
    ataturk:"Ataturk university.",
    anadolu:"Anadolu university.",
    bahcesehir:"Bahcheshehir university.",
    bartin:"Bartyn university.",
    baskent:"Bashkent university.",
    ayil:"Ankara Yyldyrym Bayezit university.",
    bezmialem:"Bezmialem Vakyf university.",
    bilecik:"Bilejik Sheyh Edebali university.",
    bilkent:"Bilkent university.",
    bogazici:"Bogazichi university.",
    bolu:"Bolu Abant Izzat Baysal university.",
    bozok:"Bozok university.",
    bteknik:"Bursa Technik university.",
    buludag:"Bursa Uludag university.",
    cankaya:"Chankaya university.",
    cankiri:"Chankiri Karatekin university.",
    cukurova:"Chukurova university.",
    dicle:"Dijle university.",
    dokuz:"Dokuz Eylul university.",
    duzce:"Duzje university.",
    ege:"Ege university.",
    erciyes:"Erjiyes university.",
    firat:"Fyrat university.",
    gazi:"Gazi university.",
    gteknik:"Gebze Technik university.",
    hacettepe:"Hajettepe university.",
    bilgi: "Istanbul Bilgi university.",
    medipol:"Istanbul Medipol university.",
    aydin:"Istanbul Aydin university.",
    gelisim:"Istanbul Gelishim university.",
    istinye:"Istinye university.",
    kadir:"Kadir Has university.",
    iyasar:"Izmir Yashar university.",
    medeniyet:"Istanbul culture  university.",
    iteknik:"Istanbul Technik university.",
    istanbul:"Istanbul university.",
    cerrahpasa:"Istanbul university, Jerrahpasha.",
    izteknik:"Izmir high Technik Institude.",
    karabuk:"Karabuk university.",
    koc:"Koch university.",
    manisa:"Manisa Jelal B. university.",
    necmettin:"Nejmeddin E. university.",
    odt:"Orta Dogu Technik university",
    ozyegin:"Ozyegin university.",
    sabanci:"Sabanjy university.",
    sakarya:"Sakarya university.",
    seljuk:"Seljuk university.",
    tobb:"TOBB E. and T. university.",
    yildiz:"Yildiz technik university.",
    sb:"Health Science university.",
    kocatepe:"Afyon Kojatepe University",
    menderes:"Adnan Menderes University",
    burdur:"Burdur Mehmet A. E. University",
    dumlupinar:"Dumlupinar University",
    binali:"Erzinjan Binali Yyldyrym University",
    eskisehir:"Eskisehir Osmangazi University",
    estechnik:"Eskisehir Technik University",
    gaziantep:"Gaziantep University",
    hitit:"Hitit University",
    inonu:"Inonu University",
    izekonomi:"Izmir Ekonomi University",
    katechnik:"Karadeniz Technik University",
    kastomonu:"Kastomonu University",
    kirikkale:"Kyrykkale University",
    ahi:"Kyrshehir Ahi Evran University",
    kojaeli:"Kojaeli University",
    kteknik:"Konya Technik University",
    marmara:"Marmara University",
    mersin:"Mersin University",
    mus:"Mush Alp-Arslan University",
    mugla:"Mugla Sykty Kochman University",
    nigde:"Nigde O. H.  University",
    ondokuz:"Ondokuz Mayis University",
    ordu:"Ordu University",
    pamukkale:"Pamukkale University",
    rejep:"Rejep Tayip Erdogan University",
    scumhuriyet:"Sivas Cumhuriyet University",
    suleyman:"Suleyman Demirel University",
    tokat:"Tokat Gaziosmanpasha University",
    trakya:"Trakya University",
    usak:"Ushak University",
    van:"Van yuzunji yyl University",
    yeditepe:"Yeditepe University",
    zonguldak:"Zonguldak B. E. University",
    AlpArslan:"Adana Alp-Arslan T. University",
    abdullah:"Abdullah Gul University",
    adiyaman:"Adyyaman University",
    agri:"Agri I. Ch. University",
    keykubat:"Alanya Aladdin K. University",
    amasya:"Amasya University",
    asosyal:"Ankara Social Science University",
    ardahan:"Ardahan University",
    artvin:"Artvin Choruh University",
    alanya:"Alanya H. E. Pasha University",
    anka:"Anka Technology University",
    avrasya:"Avrasya University",
    abilim:"Ankara Science University",
    balikesir:"Balykesir University",
    bandirmaonyedieylul:"Bandyrma Onyedi Eylul University",
    bayburt:"Bayburt University",
    bingol:"Bingol University",
    biruni:"Biruni University",
    beren:"Bitlis Eren University",
    beykent:"Beykent University",
    beykoz:"Beykoz University",
    con:"Chanakkale Onsekiz Mart University",
    cag:"Chag University",
    dumlupinar:"Dumlupinar University",
    dogus:"Dogush University",
    etechnik:"Erzurum Technik University",
    fenerbahche:"Fenerbahche University",
    fsm:"Fatih Sultan M. Vakyf University",
    galata:"Galatasaray University",
    giresun:"Giresun University",
    gumushhane:"Gumushhane University",
    hakkari:"Hakkari University",
    hatay:"Hatay Mustapha Kemal University",
    halic:"Halich University",
    hkalyoncu:"Hasan Kalyoncu University",
    igdir:"Ygdyr University",
    isik:"Yshyk University",
    iteknikz:"Iskenderun Technik University",
    arel:"Istanbul Arel University",
    atlas:"Istanbul Atlas University",
    Iesenyurt:"Istanbul Esenyurt University",
    gedik:"Istanbul Gedik University",
    kent:"Istanbul Kent University",
    nisantasi:"Istanbul Nishantashy University",
    ayvansaray:"Istanbul Ayvansaray University",
    topkapi:"Istanbul Topkapy University",
    yeniyuzyil:"Istanbul Yeni Yuzyyl University",
    okan:"Istanbul Okan University",
    rumeli:"Istanbul Rumeli University",
    zaim:"Istanbul S. Zaim University",
    sehir:"Istanbul Shehir University",
    ticaret:"Istanbul Tijaret University",
    itinaztepe:"Izmir Tynaztepe University",
    bakircay:"Izmir Bakirchay University",
    idemokrasy:"Izmir Demokrasy University",
    ikc:"Izmir K. C. University",
    kafkas:"Kafkas University",
    ksi:"Kahramanmarash S. I. University",
    km:"Karamanoglu M. University",
    kyrklareli:"Kyrklareli University",
    kilis:"Kilis 7 Aralik University",
    ksaglikbilimler:"Kutahya Health Science University",
    gidatarim:"Gyda ve Tarym University",
    lokmanhekim:"Doctor Hekim University",
    mto:"Malatya T. O. University",
    msguzelsanatlar:"Mimar S. Guzel Sanatlar University",
    millisavunma:"Milli Savunma University",
    maltepe:"Maltepe University",
    mef:"Mef University",
    nhbv:"Nevshehir H. B. Veli University",
    okorkutata:"Osmaniye Korkut Ata University",
    pirireis:"Piri Reis University",
    polakademy:"Police  Academyfgn",
    uygulamalibilimler:"Sakarya Applied Sciences  University",
    siirt:"Siirt  University",
    sinop:"Sinop  University",
    sanko:"Sanko University",
    tnamikkemal:"Tekirdag N. K.  University",
    trabzon:"Trabzon  University",
    tarsus:"Tarsus University",
    tg:"Turkish German University",
    thk:"Turkish Air Authority University",
    tedu:"TED University",
    shirnak:"Shirnak  University",
    ufuk:"Ufuk University",
    uskudar:"Uskudar University",
    yalova:"Yalova  University",
    highihtisas:"Yuksek Ihtisas University",
    




    //KIMLIK
    aboutmainTextO:"Student identity",
    aboutmainTextI:"Worker identity",
     aboutKim:"About",
     aboutKimlikHow:"HOW TO GET IDENTITY?",
     aboutVizaHow:"HOW TO GET VISA?",
     aboutmainTextK:"Short time identity",
     doc:"Documents to get identity:",
     docv:"Documents to get visa",

     //dannyyKnopka
     contact:"Contact us",
     chooseP:"Please choose one",
     studyA:"Apply for study",
     transkript:"Upload Transcript",
     grades:"Upload Grades",


  },
  ru: {
    mainText: "Давайте откроем потенциал.",
    mainP: "Приезжайте учиться за границу, с Глобалом.",
    about: "О нас",
    vision:"Наше видение",
    mission:"Наша миссия",
    aboutT:"Компания Global Group предоставляет экспертные консалтинговые услуги в сфере образования и международного трудоустройства в Турции и Европе с 2018 года. С момента нашего основания мы помогли тысячам людей получить образование своей мечты и построить успешную карьеру за рубежом. Наша цель — помочь студентам, молодым специалистам и соискателям раскрыть свой потенциал и помочь им найти правильный путь к достижению целей. Благодаря широкой сети учебных заведений, надежным партнерам и опытной команде консультантов мы предлагаем индивидуальные и стратегические решения, разработанные с учетом потребностей каждого. В Global Group мы больше, чем просто консалтинговая компания — мы стремимся стать вашим партнером на этом пути. От планирования образования до трудоустройства мы поддерживаем вас на каждом этапе, обеспечивая прозрачность, доверие и профессионализм.",
    visionT:"Наша цель — стать ведущей силой в этом секторе по всей Турции и Европе, помогая людям стать компетентными, информированными и уверенными в себе на глобальном уровне.",
    missionT:"Наша миссия — помогать нашим клиентам принимать правильные решения и уверенно идти к светлому будущему.",
    partner: "Партнёр",
    Universities: "Университеты",
    viza:"Визовые процедуры",
    aboutmainTextTV:"Турицтическая Виза",
    aboutmainTextIV:"Рабочая Виза",
    aboutmainTextTrV:"Транзит Виза",
    aboutmainTextMV:"Семейная Виза",
    aboutmainTextVV:"VIP  Виза",
    aboutmainTextOV:"Студенческая Виза",
    residence:"Резиденция",
    service:" Услуги",

    apply:"ЗАЯВЛЕНИЕ",
    How: "Как подать заявку?",
    HowH1: "1. Если вы хотите учиться в Турции — это легко.",
    HowH2: "1. Нажмите на кнопку выше с надписью 'GLOBAL'.",
    HowH3: "2. Затем заполните форму и нажмите 'Отправить'.",
    HowH4: "3. Пожалуйста, ЖДИТЕ. Мы вам позвоним.",
    HowH5: "4. Если мы не позвонили — отправьте email или sms.",
    agencyName:"Название вашего агентства, если у вас есть:",
    adresse:"Адрес : Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"Все Университеты",
    approvedUni:"Одобренные Универцитеты ",

    cost: "Цены:",
    locationI: "Местоположение: Стамбул",
    locationAn:"Местоположение: Анкара",
    locationIz:"Местоположение: Измир",
    locationKon:"Местоположение: Конья",
    locationAnt:"Местоположение: Анталя",
    locationAk:"Местоположение: Аксрай",
    locationE:"Местоположение: Эрзурум",
    locationEs:"Местоположение: Эскишэхир",
    locationB:"Местоположение: Бурса",
    locationYo:"Местоположение: Ёзгат",
    locationBo:"Местоположение: Болу",
    locationBil:"Местоположение: Биледжик",
    locationCh:"Местоположение: Чанкири",
    locationAd:"Местоположение: Адана",
    locationDi:"Местоположение: Диярбакир",
    locationDu:"Местоположение: Дюздже",
    locationKa:"Местоположение: Кайцеры",
    locationEl:"Местоположение: Элазиг",
    locationKo:"Местоположение: Коджаэли",
    locationKar:"Местоположение: Карабюк",
    locationSak:"Местоположение: Сакаря",
    locationM:"Местоположение: Маниса",
    locationMal:"Местоположение: Малатья",
    locationAf:"Местоположение: Афён",
    locationAy:"Местоположение: Айдын",
    locationBur:"Местоположение: Бурдур",
    locationKut:"Местоположение: Кютахя",
    locationErz:"Местоположение: Эрзинджан",
    locationCor:"Местоположение: Чорум",
    locationGaz:"Местоположение: Газиантеп",
    locationTra:"Местоположение: Трабзон",
    locationKas:"Местоположение: Кастамону",
    locationKyr:"Местоположение: Кыррыккале",
    locationKir:"Местоположение: Кыршехир",
    locationMus:"Местоположение: Мущ",
    locationMug:"Местоположение: Мугла",
    locationMer:"Местоположение: Мэрсин",
    locationNig:"Местоположение: Нигле",
    locationOr:"Местоположение: Орду",
    locationSam:"Местоположение: Самсун",
    locationDen:"Местоположение: Денизли",
    locationRiz:"Местоположение: Ризе",
    locationSiv:"Местоположение: Сивас",
    locationIsp:"Местоположение: Спарта",
    locationTok:"Местоположение: Токат",
    locationEd:"Местоположение: Эдирне",
    locationUs:"Местоположение: Ушак",
    locationVan:"Местоположение: Ван",
    locationZon:"Местоположение: Зонгулдак",
    locationAdy:"Местоположение: Адыяман",
    locationAgr:"Местоположение: Агры",
    locationAma:"Местоположение: Амася",
    locationArd:"Местоположение: Ардахан",
    locationArt:"Местоположение: Артвин",
    locationBal:"Местоположение: Балыкэсир",
    locationBay:"Местоположение: Байбурт",
    locationBin:"Местоположение: Бингол",
    locationBit:"Местоположение: Битлис",
    locationCha:"Местоположение: Чанаккале",
    locationGir:"Местоположение: Гиресун",
    locationGum:"Местоположение: Гумушхане",
    locationHak:"Местоположение: Хаккари",
    locationIgd:"Местоположение: Ыгдир",
    locationIsk:"Местоположение: Искендерун",
    locationKars:"Местоположение: Карс",
    locationKah:"Местоположение: Кахраманпаша",
    locationKara:"Местоположение: Караман",
    locationKyrk:"Местоположение: Кыркларели",
    locationKil:"Местоположение: Килис",
    locationNev:"Местоположение: Невшехир",
    locationOsm:"Местоположение: Османие",
    locationSii:"Местоположение: Сиирт",
    locationSin:"Местоположение: Синоп",
    locationShi:"Местоположение: Ширнак",
    locationTek:"Местоположение: Текирдаг",
    locationTrab:"Местоположение: Трабзон",
    locationTun:"Местоположение: Тунджели",
    locationYal:"Местоположение: Ялова",
    locationAl:"Местоположение: Аланя",
    locationTar:"Местоположение: Тарсус",
    


    altinbas:"Унв. Алтынбаш.",
    atilim:"Унв. Атылым.",
    acibadem:"Унв. Аджыбадем.",
    akdeniz:"Унв. Акдениз.",
    aksaray:"Унв. Аксарай.",
    ankara:"Унв. Анкара.",
    ataturk:"Унв. Ататюрк.",
    anadolu:"Унв. Анадолу.",
    bahcesehir:"Унв. Бахчешехир.",
    bartin:"Унв. Бартын.",
    baskent:"Унв. Башкент.",
    ayil:"Унв. Анкара Йилдирим Баезит",
    bezmialem:"Унв. Безмиалем Вакиф.",
    bilecik:"Унв. Биледжик Шейх Эдэбали.",
    bilkent:"Унв. Билкент.",
    bogazici:"Унв. Богазичи.",
    bolu:"Унв. Болу Абант Иззат Байцал.",
    bozok:"Унв. Бозок.",
    bteknik:"Унв. Бурса Текник.",
    buludag:"Унв. Бурса Улудаг.",
    cankaya:"Унв. Чанкайа.",
    cankiri:"Унв. Чанкири Каратекин.",
    cukurova:"Унв. Чукурова.",
    dicle:"Унв. Диджле.",
    dokuz:"Унв. Докуз Эйлюл.",
    duzce:"Унв. Дюздже.",
    ege:"Унв. Эгэ.",
    erciyes:"Унв. Зрджиес.",
    firat:"Унв. Фырать.",
    gazi:"Унв. Гази.",
    gteknik:"Унв. Гебзе Текник.",
    hacettepe:"Унв. Хаджеттепе.",
    bilgi: "Стамбульский унв. Билги.",
    medipol:"Стамбульский унв. Медипол.",
    aydin:"Стамбульский унв. Айдын.",
    gelisim:"Стамбульский унв. Гелишим.",
    istinye:"Унв. Истинье.",
    kadir:"Унв. Кадир Хас.",
    iyasar:"Унв. Измир Яшар.",
    medeniyet:"Стамбулский Унв. Културы.",
    iteknik:"Станбулский Технический Унв.",
    istanbul:"Унв. Стамбул.",
    cerrahpasa:"Унв. Станбул, Джеррахпаша.",
    izteknik:"Измирский высший  Технический Институт.",
    karabuk:"Унв. Карабюк.",
    koc:"Унв. Коч.",
    manisa:"Унв. Маниса Джелал Б.",
    necmettin:"Унв. Неджметтин Е.",
    odt:"Унв. Орта Догу Текник.",
    ozyegin:"Унв. Озегин.",
    sabanci:"Унв. Сабанджи.",
    sakarya:"Унв. Сакарья.",
    seljuk:"Унв. Селджук.",
    tobb:"Унв. ТОББ Е. и Т..",
    yildiz:"Унв. Йилдиз Текник.",
    sb:"Унв. Медицинских наук.",
    kocatepe:"Унв. Афён Коджатепе.",
    menderes:"Унв. Аднан Мендерес.",
    burdur:"Унв. Бурдур Мэхмэт А. Э.",
    dumlupinar:"Унв. Думлупинар.",
    binali:"Унв. Эрзинджан Биналы Йылдырым.",
    eskisehir:"Унв. Эскишехир Османгази.",
    estechnik:"Эскишехирский Технический Унв.",
    gaziantep:"Унв. Газиантеп.",
    hitit:"Унв. Хитит.",
    inonu:"Унв. Инону.",
    izekonomi:"Измирский Экономический Унв.",
    katechnik:"Унв. Карадениз Техник",
    kastomonu:"Кастамонский Унв.",
    kirikkale:"Унв. Кырыккале.",
    ahi:"Унв. Кыршехир Ахи Эвран.",
    kojaeli:"Унв. Коджаэли",
    kteknik:"Конийсуий Технический Унв.",
    marmara:"Унв. Мармара.",
    mersin:"Мерцинский Унв.",
    mus:"Унв. Мущ Алп-Арслан.",
    mugla:"Унв. Мугла Сыкты Кочман.",
    nigde:"Унв. Нигде О. Х.",
    ondokuz:"Унв. Ондокуз Майис.",
    ordu:"Унв. Орду.",
    pamukkale:"Унв. Памуккале.",
    rejep:"Унв. Реджеп Тайип Эрдоган.",
    scumhuriyet:"Унв. Сивас Джумхуриеть.",
    suleyman:"Унв. Сулейман Демирел.",
    tokat:"Унв. Токат Газиосманпаша.",
    trakya:"Унв. Тракя.",
    usak:"Ушакский Унв.",
    van:"Ван Юз Йылинджи Унв.",
    yeditepe:"Унв. Едитепе.",
    zonguldak:"Унв. Зонгулдак Б. Э.",
    AlpArslan:"Унв. Адана Алп-Арслан Т.",
    abdullah:"Унв. Абдуллы Гюля",
    adiyaman:"Унв. Адыяман",
    agri:"Унв. Агры И. Ч. ",
    keykubat:"Унв. Аланя Аладдин К.",
    amasya:"Унв. Амася",
    asosyal:"Унв. Социальные науки Анкары",
    ardahan:"Унв. Ардахан",
    artvin:"Унв. Артвин Чорух",
    alanya:"Унв.Аланя Х. Е. Паща",
    anka:"Унв. Анка Технология",
    avrasya:"Унв. Аврася",
    abilim:"Анкарийский  Унв. Наук ",
    balikesir:"Балыкесирский Унв.",
    bandirmaonyedieylul:"Унв. Бандырма Онеди Эйлюл",
    bayburt:"Унв. Байбурт",
    bingol:"Унв. Бингол",
    biruni:"Унв. Бируни ",
    beren:"Унв. Битлис Эрэн",
    beykent:"Унв. Бэйкэнт",
    beykoz:"Унв. Бейкоз",
    con:"Унв. Чанккале Он Секиз Март",
    cag:"Унв. Чаг",
    dumlupinar:"Унв. Думлупинар",
    dogus:"Унв. Догуш",
    etechnik:"Эрзурумский Технический Унв. ",
    fenerbahche:"Унв. Фенербахче",
    fsm:"Унв. Фатих Султан М. Вакыфй",
    galata:"Унв. Галатасарай",
    giresun:"Унв. Гиресун",
    gumushhane:"Унв. Гюмушхане",
    hakkari:"Унв. Хаккари",
    hatay:"Унв. Хатай Мустафа Кемал",
    halic:"Унв. Халич",
    hkalyoncu:"Унв. Хасан Калёнджу",
    igdir:"Унв. Ыгдыр",
    isik:"Унв. Ышык",
    iteknikz:"Искендерунский Технический Унв.",
    arel:"Стамбулский Унв. Арэл",
    atlas:"Стамбулский Унв. Атлас",
    Iesenyurt:"Стамбулский Унв. Эсенюрт",
    gedik:"Стамбулский Унв. Гедик",
    kent:"Стамбулский Унв. Кент",
    nisantasi:"Стамбулский Унв. Нишанташы",
    ayvansaray:"Стамбулский Унв. Айвансарай",
    topkapi:"Стамбулский Унв. Топкапы",
    yeniyuzyil:"Стамбулский Унв. Ени Юз Йыл",
    okan:"Стамбулский Унв. Окан",
    rumeli:"Стамбулский Унв. Румели",
    zaim:"Стамбулский Унв. С. Заим",
    sehir:"Стамбулский Шэхир Унв.",
    ticaret:"Стамбулский Унв. Тиджарет",
    itinaztepe:"Измирский Унв. Тыназтепе",
    bakircay:"Измирский Унв. Бакирчай",
    idemokrasy:"Измирский Демократический Унв.",
    ikc:"Измирский К. Ч. Унв.",
    kafkas:"Унв. Кавказ",
    ksi:"Унв. Кахраманмараш С. И.",
    km:"Унв. Караманоглу",
    kyrklareli:"Унв. Кыркларэли",
    kilis:"Унв. Килис 7 Аралик",
    ksaglikbilimler:"Унв. Медицинские науки Кютахьи",
    gidatarim:"Унв. Гыда и Тарым",
    lokmanhekim:"Унв. Локман Хеким",
    mto:"Унв. Малатья Т. О.",
    msguzelsanatlar:"Унв. Мимар С. Гузел Санатлар",
    millisavunma:"Унв. Милли Савунма",
    maltepe:"Унв. Малтепе",
    mef:"Унв. Мэф",
    nhbv:"Унв. Невшехир Н. Б. Вели",
    okorkutata:"Унв. Османие Коркут Ата",
    pirireis:"Унв. Пири Реис",
    polakademy:"Полисейская Академия",
    uygulamalibilimler:"Унв. Сакарья Прикладные Науки",
    siirt:"Унв. Сиирт",
    sinop:"Унв. Синоп",
    sanko:"Унв. Санко",
    tnamikkemal:"Унв.  Текирдаг Н. К.",
    trabzon:"Унв. Трабзон",
    tarsus:"Унв. Тарсус",
    tg:"Турка-Немецкий Унв.",
    thk:"Унв. Турецкая Авиационная Ассоциация",
    tedu:"Унв. ТЕД",
    shirnak:"Унв. Щирнак",
    ufuk:"Унв. Уфук",
    uskudar:"Унв. Ускюдар",
    yalova:"Унв. Ялова",
    highihtisas:"Унв. Юксек Ихтиас",



     //KIMLIK
     aboutmainTextO:"Студенческий паспорт",
     aboutmainTextI:"Рабочий паспорт",
     aboutmainTextK:"Коротко временний паспорт",
     aboutKim:"Об этом",
     aboutKimlikHow:"КАК ПОЛУЧИТЬ ПАСПОРТ?",
     aboutVizaHow:"КАК ПОЛУЧИТЬ ВИЗУ?",     
     doc:"Документы для получения паспорта:",
     docv:"Документы для получения визы",
     
     //dannyyKnopka
     contact:"Свяжись с нами",
     chooseP:"Пожалуйста Выберите Один",
     studyA:"Ради Учёбы",
     transkript:"Добавьте Транскрипт",
     grades:"Добавьте Аттестат",
     
   
      },
  tr: {
    mainText: "Potansiyeli keşfedelim.",
    mainP: "Global ile yurtdışında okumaya gelin.",
    about: "Hakkımızda",
    vision:"Vizyonumuz",
    mission:"Misyonumuz",
    aboutT:"Global Group, 2018 yılından bu yana Türkiye ve Avrupa genelinde eğitim ve uluslararası istihdam alanlarında uzman danışmanlık hizmetleri sunmaktadır. Kuruluşumuzdan bu yana binlerce kişinin hayalindeki eğitimi almasına ve yurt dışında başarılı kariyerler inşa etmesine yardımcı olduk. Amacımız, öğrencilerin, genç profesyonellerin ve iş arayanların potansiyellerini keşfetmelerine ve hedeflerine doğru yolda ilerlemelerine yardımcı olmaktır. Geniş kurum ağımız, güvenilir ortaklarımız ve deneyimli danışman ekibimizle, her bireye özel, kişiselleştirilmiş ve stratejik çözümler sunuyoruz. Global Group olarak, sıradan bir danışmanlık firmasından çok daha fazlasıyız; bu yolculukta ortağınız olmayı hedefliyoruz. Eğitim planlamasından iş yerleştirmeye kadar, şeffaflık, güven ve profesyonellikle her adımda size destek oluyoruz.",
    visionT:"Vizyonumuz, bireylerin küresel ölçekte yetkin, bilgili ve özgüvenli bireyler haline gelmelerine yardımcı olarak Türkiye ve Avrupa çapında sektörde öncü bir güç olmaktır.",
    missionT:"Misyonumuz, müşterilerimizin doğru kararlar almalarına ve daha parlak bir geleceğe doğru güvenle yürümelerine rehberlik etmektir.",
    partner: "Ortak",
    Universities: "Üniversiteler",
    viza:"Vize işlemleri",
    aboutmainTextTV:"Turist Vizesi",
    aboutmainTextIV:"Çalışma Vizesi",
    aboutmainTextTrV:"Transit Vizesi",
    aboutmainTextMV:"Aile Vizesi",
    aboutmainTextVV:"VIP  Vize",
    aboutmainTextOV:"Öğrenci Vizesi",
    residence:"Ikamet işlemleri",
    apply:"BAŞVUR",
    How: "Nasıl başvurulur?",
    HowH1: "1. Türkiye'de okumak istiyorsanız bu çok kolay.",
    HowH2: "1. Yukarıdaki 'GLOBAL' butonuna tıklayın.",
    HowH3: "2. Formu doldurun ve 'Gönder' butonuna tıklayın.",
    HowH4: "3. Lütfen BEKLEYİN. Sizi arayacağız.",
    HowH5: "4. Aramazsak, bize e-posta veya sms gönderin.",
    labelP: "Bölüminizi seçiniz:",
    agencyName:"Eğer varsa, acentenizin adı:",
    adresse:"Adres: Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"Tüm Üniversiteler",
    approvedUni:"Onaylanan Üniversiteler",
    service:"Hizmetlerimiz",

    cost: "Fiyatlar:",
  locationI: "Yer: İstanbul.",
  locationAn:"Yer: Ankara",
  locationIz:"Yer: Izmir",
  locationKon:"Yer: Konya",
  locationAnt:"Yer: Antalya",
  locationAk:"Yer: Aksaray",
  locationE:"Yer: Erzurum",
  locationEs:"Yer: Eskişehir",
  locationB:"Yer: Bursa",
  locationYo:"Yer: Yozgat",
  locationBo:"Yer: Bolu",
  locationBil:"Yer: Bilecik",
  locationCh:"Yer: Çankırı",
  locationAd:"Yer:  Adana",
  locationDi:"Yer: Diyarbakır",
  locationDu:"Yer: Düzce",
  locationKa:"Yer: Kayseri",
  locationEl:"Yer: Elaziğ",
  locationKo:"Yer: Kocaeli",
  locationKar:"Yer: Karabük",
  locationSak:"Yer: Sakarya",
  locationM:"Yer: Manisa",
  locationMal:"Yer: Malatya",
  locationAf:"Yer: Afyon",
  locatonAy:"Yer: Aydın",
  locationBur:"Yer: Burdur",
  locationKut:"Yer: Kütahya",
  locationErz:"Yer: Erzincan",
  locationCor:"Yer: Çorum",
  locationGaz:"Yer: Gaziantep",
  locationTra:"Yer: Trabzon",
  locationKas:"Yer: Kastamonu",
  locationKyr:"Yer: Kırrıkkale",
  locationKir:"Yer: Kırşehir",
  locationMus:"Yer: Muş",
  locationMug:"Yer: Muğla",
  locationMer:"Yer: Mersin",
  locationNig:"Yer: Niğde",
  locationOr:"Yer: Ordu",
  locationSam:"Yer: Samsun",
  locationDen:"Yer: Denizli",
  locationRiz:"Yer: Rize",
  locationSiv:"Yer: Sivas",
  locationIsp:"Yer: Isparta",
  locationTok:"Yer: Tokat",
  locationEd:"Yer: Edirne",
  locationUs:"Yer: Uşak",
  locationVan:"Yer: Van",
  locationZon:"Yer: Zonguldak",
  locationAdy:"Yer: Adyyaman",
    locationAgr:"Yer: Agrı",
    locationAma:"Yer: Amasya",
    locationArd:"Yer: Ardahan",
    locationArt:"Yer: Artvin",
    locationBal:"Yer: Balıkesir",
    locationBay:"Yer: Bayburt",
    locationBin:"Yer: Bingöl",
    locationBit:"Yer: Bitlis",
    locationCha:"Yer: Çanakkale",
    locationGir:"Yer: Giresun",
    locationGum:"Yer: Gümüşhane",
    locationHak:"Yer: Hakkari",
    locationIgd:"Yer: Igdır",
    locationIsk:"Yer: Iskenderun",
    locationKars:"Yer: Kars",
    locationKah:"Yer: Kahramanmaraş",
    locationKara:"Yer: Karaman",
    locationKyrk:"Yer: Kırklareli",
    locationKil:"Yer: Kilis",
    locationNev:"Yer: Nevşehir",
    locationOsm:"Yer: Osmaniye",
    locationSii:"Yer: Siirt",
    locationSin:"Yer: Sinop",
    locationShi:"Yer: Şirnak",
    locationTek:"Yer: Tekirdağ",
    locationTrab:"Yer: Trabzon",
    locationTun:"Yer: Tünceli",
    locationYal:"Yer: Yalova",
    locationAl:"Yer: Alanya",
    locationTar:"Yer: Tarsus",



  altinbas:"Altınbaş Üniversitesi.",
    atilim:"Atılım Üniversitesi.",
    acibadem:"Acıbadem Üniversitesi.",
    akdeniz:"Akdeniz Üniversitesi.",
    aksaray:"Aksaray Üniversitesi.",
    ankara:"Ankara Üniversitesi.",
    ataturk:"Atatürk Üniversitesi.",
    anadolu:"Anadolu Üniversitesi.",
    bahcesehir:"Bahçeşehir Üniversitesi.",
    bartin:" Bartın Üniversitesi.",
    baskent:"Başkent Üniversitesi.",
    ayil:"Ankara Yıldırım Bayezit Üniversitesi.",
    bezmialem:"Bezmialem Vakıf Üniversitesi.",
    bilecik:"Bilecik Şeyh Edebali Üniversitesi.",
    bilkent:"Bilkent Üniversitesi.",
    bogazici:"Boğaziçi Üniversitesi.",
    bolu:"Bolu Abant Izzat Baysal Üniversitesi.",
    bozok:"Bozok Üniversitesi.",
    bteknik:"Bursa Teknik Üniversitesi.",
    buludag:"Bursa Uludağ Üniversitesi.",
    cankaya:"Çankaya Üniversitesi.",
    cankiri:"Çankiri Karatekin Üniversitesi.",
    cukurova:"Çukurova Üniversitesi.",
    dicle:"Dicle Üniversitesi.",
    dokuz:"Dokuz Eylül Üniversitesi.",
    duzce:"Düzce Üniversitesi.",
    ege:"Ege Üniversitesi.",
    erciyes:"Erciyes Üniversitesi.",
    firat:"Fırat Üniversitesi.",
    gazi:"Gazi Üniversitesi.",
    gteknik:"Gebze Teknik Üniversitesi.",
    hacettepe:"Hacettepe Üniversitesi.",
    bilgi: "Istanbul Bilgi Üniversitesi.",
    medipol:"Istanbul Medipol Üniversitesi.",
    aydin:"Istanbul Aydın Üniversitesi.",
    gelisim:"Istanbul Gelişim Üniversitesi.",
    istinye:"Istinye Üniversitesi.",
    kadir:"Kadir Has Üniversitesi.",
    iyasar:"Izmir Yaşar Üniversitesi.",
    medeniyet:"Istanbul Medeniyet  Üniversitesi.",
    iteknik:"Istanbul Teknik Üniversitesi.",
    istanbul:"Istanbul Üniversitesi.",
    cerrahpasa:"Istanbul Üniversitesi, Cerrahpaşa.",
    izteknik:"İzmir Yüksek T. Enstitüsü.",
    karabuk:"Karabük Üniversitesi.",
    koc:"Koç Üniversitesi.",
    manisa:"Manisa Celal B. Üniversitesi.",
    necmettin:"Necmettin E. Üniversitesi.",
    odt:"Orta Doğu Teknik Üniversitesi.",
    ozyegin:"Özyegin Üniversitesi.",
    sabanci:"Sabancı Üniversitesi.",
    sakarya:"Sakarya Üniversitesi.",
    seljuk:"Selçuk Üniversitesi.",
    tobb:"TOBB E. ve T. Üniversitesi.",
    yildiz:"Yildiz teknik Üniversitesi.",
    sb:"Sağlık Bilimler Üniversitesi.",
    kocatepe:"Afyon Kocatepe Üniversitesi",
    menderes:"Adnan Menderes Üniversitesi",
    burdur:"Burdur Mehmet A. E. Üniversitesi",
    dumlupinar:"Dumlupinar Üniversitesi",
    binali:"Erzincan Binali Yıldırım Üniversitesi",
    eskisehir:"Eskişehir Osmangazi Üniversitesi",
    estechnik:"Eskişehir Teknik Üniversitesi",
    gaziantep:"Gaziantep Üniversitesi",
    hitit:"Hitit Üniversitesi",
    inonu:"Inönü Üniversitesi",
    izekonomi:"Izmir Ekonomi Üniversitesi",
    katechnik:"Karadeniz Teknik Üniversitesi",
    kastomonu:"Kastomonu Üniversitesi",
    kirikkale:"Kırıkkale Üniversitesi",
    ahi:"Kırşehir Ahi Evran Üniversitesi",
    kojaeli:"Kocaeli Üniversitesi",
    kteknik:"Konya Teknik Üniversitesi",
    marmara:"Marmara Üniversitesi",
    mersin:"Mersin Üniversitesi",
    mus:"Muş Alparslan Üniversitesi",
    mugla:"Muğla Sıktı Kochman Üniversitesi",
    nigde:"Niğde O. H.  Üniversitesi",
    ondokuz:"Ondokuz Mayis Üniversitesi",
    ordu:"Ordu Üniversitesi",
    pamukkale:"Pamukkale Üniversitesi",
    rejep:"Recep Tayıp Erdogan Üniversitesi",
    scumhuriyet:"Sivas Cumhuriyet Üniversitesi",
    suleyman:"Süleyman Demirel Üniversitesi",
    tokat:"Tokat Gaziosmanpaşa Üniversitesi",
    trakya:"Trakya Üniversitesi",
    usak:"Uşak Üniversitesi",
    van:"Van yüzünci yıl Üniversitesi",
    yeditepe:"Yeditepe Üniversitesi",
    zonguldak:"Zonguldak B. E. Üniversitesi",
    AlpArslan:"Adana Alparslan T. Üniversitesi",
    abdullah:"Abdullah Gül Üniversitesi",
    adiyaman:"Adıyaman Üniversitesi",
    agri:"Agri I. Ç. Üniversitesi",
    keykubat:"Alanya Aladdin K. Üniversitesi",
    amasya:"Amasya Üniversitesi",
    asosyal:"Ankara Sosyal Bilimler Üniversitesi",
    ardahan:"Ardahan Üniversitesi",
    artvin:"Artvin Çoruh Üniversitesi",
    alanya:"Alanya H. E. Paşa Üniversitesi",
    anka:"Anka Teknoloci Üniversitesi",
    avrasya:"Avrasya Üniversitesi",
    abilim:"Ankara Bilim Üniversitesi",
    balikesir:"Balıkesir Üniversitesi",
    bandirmaonyedieylul:"Bandırma Onyedi Eylül Üniversitesi",
    bayburt:"Bayburt Üniversitesi",
    bingol:"Bingöl Üniversitesi",
    biruni:"Biruni Üniversitesi",
    beren:"Bitlis Eren Üniversitesi",
    beykent:"Beykent Üniversitesi",
    beykoz:"Beykoz Üniversitesi",
    con:"Çanakkale Onsekiz Mart Üniversitesi",
    cag:"Çag Üniversitesi",
    dumlupinar:"Dumlupinar Üniversitesi",
    dogus:"Doğuş Üniversitesi",
    etechnik:"Erzurum Teknik Üniversitesi",
    fenerbahche:"Fenerbahçe Üniversitesi",
    fsm:"Fatih Sultan M. Vakıf Üniversitesi",
    galata:"Galatasaray Üniversitesi",
    giresun:"Giresun Üniversitesi",
    gumushhane:"Gümüşhane Üniversitesi",
    hakkari:"Hakkari Üniversitesi",
    hatay:"Hatay Mustafa Kemal Üniversitesi",
    halic:"Haliç Üniversitesi",
    hkalyoncu:"Hasan Kalyoncu Üniversitesi",
    igdir:"Igdır Üniversitesi",
    isik:"Işık Üniversitesi",
    iteknikz:"Iskenderun Teknik Üniversitesi",
    arel:"Istanbul Arel Üniversitesi",
    atlas:"Istanbul Atlas Üniversitesi",
    Iesenyurt:"Istanbul Esenyurt Üniversitesi",
    gedik:"Istanbul Gedik Üniversitesi",
    kent:"Istanbul Kent Üniversitesi",
    nisantasi:"Istanbul Nişantaşy Üniversitesi",
    ayvansaray:"Istanbul Ayvansaray Üniversitesi",
    topkapi:"Istanbul Topkapı Üniversitesi",
    yeniyuzyil:"Istanbul Yeni Yüzyıl Üniversitesi",
    okan:"Istanbul Okan Üniversitesi",
    rumeli:"Istanbul Rumeli Üniversitesi",
    zaim:"Istanbul S. Zaim Üniversitesi",
    sehir:"Istanbul Şehir Üniversitesi",
    ticaret:"Istanbul Ticaret Üniversitesi",
    itinaztepe:"Izmir Tınaztepe Üniversitesi",
    bakircay:"Izmir Bakirçay Üniversitesi",
    idemokrasy:"Izmir Demokrasy Üniversitesi",
    ikc:"Izmir K. C. Üniversitesi",
    kafkas:"Kafkas Üniversitesi",
    ksi:"Kahramanmaraş S. I. Üniversitesi",
    km:"Karamanoğlu M. Üniversitesi",
    kyrklareli:"Kırklareli Üniversitesi",
    kilis:"Kilis 7 Aralik Üniversitesi",
    ksaglikbilimler:"Kütahya Sağlık Bilimler Üniversitesi",
    gidatarim:"Gıda ve Tarım Üniversitesi",
    lokmanhekim:"Lokman Hekim Üniversitesi",
    mto:"Malatya T. O. Üniversitesi",
    msguzelsanatlar:"Mimar S. Güzel Sanatlar Üniversitesi",
    millisavunma:"Milli Savunma Üniversitesi",
    maltepe:"Maltepe Üniversitesi",
    mef:"Mef Üniversitesi",
    nhbv:"Nevşehir H. B. Veli Üniversitesi",
    okorkutata:"Osmaniye Korkut Ata Üniversitesi",
    pirireis:"Piri Reis Üniversitesi",
    polakademy:"Polis  Akademisi",
    uygulamalibilimler:"Sakarya Uygulamalı Bilimler  Üniversitesi",
    siirt:"Siirt  Üniversitesi",
    sinop:"Sinop  Üniversitesi",
    sanko:"Sanko Üniversitesi",
    tnamikkemal:"Tekirdağ N. K.  Üniversitesi",
    trabzon:"Trabzon  Üniversitesi",
    tarsus:"Tarsus Üniversitesi",
    tg:"Türkiye-Alman Üniversitesi",
    thk:"Türkiye Hava Kurumu Üniversitesi",
    tedu:"TED Üniversitesi",
    shirnak:"Şirnak  Üniversitesi",
    ufuk:"Ufuk Üniversitesi",
    uskudar:"Üsküdar Üniversitesi",
    yalova:"Yalova  Üniversitesi",
    highihtisas:"Yüksek İhtısas Üniversitesi",


     //KIMLIK
     aboutmainTextO:"Öğrenci kimlik",
     aboutmainTextI:"Işçi kimlik",
     aboutKim:"Hakkında",
     aboutKimlikHow:"KIMLIK NASIL ALINIR?",
     aboutVizaHow:"VIZA NASIL ALINIR?",
     aboutmainTextK:"Kısa dönem kimlik",
     doc:"Kimlik almak için gereken evraklar:",
     docv:" Vize almak için gereken evraklar:",
       //dannyyKnopka
       contact:"Bizimle iletişime geç",
       chooseP:"Lütfen birini seçiniz",
       studyA:"Okul için",
       transkript:"Transkripti ýükleyin",
       grades:"Notları ýükleyin",
  },
  tu: {
    mainText: "Geliň potensialy açalyň.",
    mainP: "Global bilen daşary ýurda okuwa geliň.",
    about: "Biz barada",
    vision:"Görüşimiz",
    mission:"Biziň wezipämiz",
    aboutT:"Global Topar, 2018-nji ýyldan bäri Türkiýe we Ýewropada bilim we halkara iş üpjünçiligi boýunça hünärmenlere maslahat beriş hyzmatlaryny hödürleýär. Döredileli bäri müňlerçe adama  arzuwlaryny dowam etdirmäge we daşary ýurtlarda üstünlikli karýera gurmaga kömek etdik. Biziň maksadymyz, okuwçylara, ýaş hünärmenlere we iş gözleýänlere öz mümkinçiliklerini açmak we maksatlaryna dogry ýolda ugrukdyrmak. Guramalaryň giň ulgamy, ynamdar hyzmatdaşlar we tejribeli geňeşçiler topary bilen, her bir adama laýyklaşdyrylan şahsy we strategiki çözgütleri hödürleýäris. Global Toparda biz diňe bir maslahat beriş firmasy däl, bu syýahatda siziň hyzmatdaşyňyz bolmagy maksat edinýäris. Bilimi meýilleşdirmekden başlap, işe ýerleşmeklige çenli her ädimde aç-açanlyk, ynam we hünär ussatlygy bilen sizi goldaýarys.",
    visionT:"Biziň gözýetimimiz, şahsyýetlere dünýä derejesinde başarnykly,  we ynamly bolmaga kömek etmek bilen Türkiýe we Ýewropa boýunça bu pudakda öňdebaryjy güýç bolmak.",
    missionT:"Biziň wezipämiz, müşderilerimize dogry karar bermekgine komek etmek we olaryň ýagty geljege ynamly ýöremegidir.",
    partner: "Işdeşlik",
    Universities: "Uniwersitetler",
    residence:"Ikamet işleri",
    apply:"ÝÜZ TUTUŇ",
    How: "Nädip ýüz tutmaly?",
    HowH1: "1. Türkiýede okamak isleseňiz bu örän aňsat.",
    HowH2: "1. Ýokardaky 'GLOBAL' düwmesine basyň.",
    HowH3: "2. Formany dolduryň we 'Iber' düwmesine basyň.",
    HowH4: "3. Garaşyň. Biz size jaň ederis.",
    HowH5: "4. Eger biz jaň etmedik bolsak, bize e-poçta ýa-da sms iberiň.",
    labelP: "Bölümıňizi saýlaň:",
    agencyName:"Agentligiňiziň ady, eger bar bolsa:",
    adresse:"Salgymyz: Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"Hemme Üniwersitetler",
    approvedUni:"Tassyklanýan Üniwersitetler",
    service:"Hyzmatlarymyz",
    viza:"Viza işleri",
    aboutmainTextTV:"Turist Vizasy",
    aboutmainTextIV:"Işçi Vizasy",
    aboutmainTextTrV:"Transit Vizasy",
    aboutmainTextMV:"Maşgala Vizasy",
    aboutmainTextVV:"VIP  Viza",
    aboutmainTextOV:"Talyp Vizasy",
    cost: "Bahalar:",


    locationI: "Yeri: İstanbul.",
    locationAn:"Yeri: Ankara",
    locationIz:"Yeri: Izmir",
  locationKon:"Yeri: Konýa",
  locationAnt:"Yeri: Antalýa",
  locationAk:"Yeri: Aksaraý",
  locationE:"Yeri: Erzurum",
  locationEs:"Yeri: Eskişehir",
  locationB:"Yeri: Bursa",
  locationYo:"Yeri: Ýozgat",
  locationBo:"Yeri: Bolu",
  locationBil:"Yeri: Bilejik",
  locationCh:"Yeri: Çankyry",
  locationAd:"Yeri:  Adana",
  locationDi:"Yeri: Diýarbekir",
  locationDu:"Yeri: Düzje",
  locationKa:"Yeri: Kaýseri",
  locationEl:"Yeri: Elazig",
  locationKo:"Yeri: Kojaeli",
  locationKar:"Yeri: Karabük",
  locationSak:"Yeri: Sakarýa",
  locationM:"Yeri: Manisa",
  locationMal:"Yeri: Malatýa",
  locationMer:"Yeri: Mersin",
  locationAf:"Yeri: Afýon",
  locatonAy:"Yeri: Aýdyň",
  locationBur:"Yeri: Burdur",
  locationKut:"Yeri: Kütahya",
  locationErz:"Yeri: Erzinjan",
  locationCor:"Yeri: Çorum",
  locationGaz:"Yeri: Gaziantep",
  locationTra:"Yeri: Trabzon",
  locationKas:"Yeri: Kastamonu",
  locationKyr:"Yeri: Kyrrykkale",
  locationKir:"Yeri: Kyrşehir",
  locationMus:"Yeri: Muş",
  locationMug:"Yeri: Mugla",
  locationNig:"Yeri: Nigde",
  locationOr:"Yeri: Ordu",
  locationSam:"Yeri: Samsun",
  locationDen:"Yeri: Deňizli",
  locationRiz:"Yeri: Rize",
  locationSiv:"Yeri: Sivas",
  locationIsp:"Yeri: Isparta",
  locationTok:"Yeri: Tokat",
  locationEd:"Yeri: Edirne",
  locationUs:"Yeri: Uşak",
  locationVan:"Yeri: Wan",
  locationZon:"Yeri: Zonguldak",
  locationAgr:"Yer: Agry",
  locationAma:"Yer: Amasýa",
  locationArd:"Yer: Ardahan",
  locationArt:"Yer: Artvin",
  locationBal:"Yer: Balykesir",
  locationBay:"Yer: Baýburt",
  locationBin:"Yer: Bingöl",
  locationBit:"Yer: Bitlis",
  locationCha:"Yer: Çanakkale",
  locationGir:"Yer: Giresun",
  locationGum:"Yer: Gümüşhane",
  locationHak:"Yer: Hakkari",
  locationIgd:"Yer: Ygdyr",
  locationIsk:"Yer: Iskenderun",
  locationKars:"Yer: Kars",
  locationKah:"Yer: Kahramanmaraş",
  locationKara:"Yer: Karaman",
  locationKyrk:"Yer: Kyrklareli",
  locationKil:"Yer: Kilis",
  locationNev:"Yer: Newşehir",
  locationOsm:"Yer: Osmaniýe",
  locationSii:"Yer: Siirt",
  locationSin:"Yer: Sinop",
  locationShi:"Yer: Şirnak",
  locationTek:"Yer: Tekirdag",
  locationTrab:"Yer: Trabzon",
  locationTun:"Yer: Tünjeli",
  locationYal:"Yer: Yalowa",
  locationAl:"Yer: Alanýa",
  locationTar:"Yer: Tarsus",

  altinbas:"Altynbaş Üniwersiteti.",
  atilim:"Atylym Üniwersiteti.",
  acibadem:"Ajybadem Üniwersiteti.",
  akdeniz:"Akdeňiz Üniwersiteti.",
  aksaray:"Aksaraý Üniwersiteti.",
  ankara:"Ankara Üniwersiteti.",
  ataturk:"Atatürk Üniwersiteti.",
  anadolu:"Anadoly Üniwersiteti.",
  bahcesehir:"Bahçeşehir Üniwersiteti.",
  bartin:" Bartyn Üniwersiteti.",
  baskent:"Başkent Üniwersiteti.",
  ayil:"Ankara Yyldyrym Baýezid Üniwersiteti.",
  bezmialem:"Bezmialem Vakyf Üniwersiteti.",
  bilecik:"Bilejik Şeyh Edebali Üniwersiteti.",
  bilkent:"Bilkent Üniwersiteti.",
  bogazici:"Bogaziçi Üniwersiteti.",
  bolu:"Bolu Abant Izzat Baýsal Üniwersiteti.",
  bozok:"Bozok Üniwersiteti.",
  bteknik:"Bursa Tehnik Üniwersiteti.",
  buludag:"Bursa Uludag Üniwersiteti.",
  cankaya:"Çankaya Üniwersiteti.",
  cankiri:"Çankiri Karatekin Üniwersiteti.",
  cukurova:"Çukuroba Üniwersiteti.",
  dicle:"Dijle Üniwersiteti.",
  dokuz:"Dokuz Eýlül Üniwersiteti.",
  duzce:"Düzje Üniwersiteti.",
  ege:"Ege Üniwersiteti.",
  erciyes:"Erjiyes Üniwersiteti.",
  firat:"Fyrat Üniwersiteti.",
  gazi:"Gazy Üniwersiteti.",
  gteknik:"Gebze Tehnik Üniwersiteti.",
  hacettepe:"Hajettepe Üniwersiteti.",
  bilgi: "Istanbul Bilgi Üniwersiteti.",
  medipol:"Istanbul Medipol Üniwersiteti.",
  aydin:"Istanbul Aydyň Üniwersiteti.",
  gelisim:"Istanbul Gelişim Üniwersiteti.",
  istinye:"Istinýe Üniwersiteti.",
  kadir:"Kadir Has Üniwersiteti.",
  iyasar:"Izmir Ýaşar Üniwersiteti.",
  medeniyet:"Istanbul Medeniýet Üniwersiteti.",
  iteknik:"Istanbul Tehnik Üniwersiteti.",
  istanbul:"Istanbul Üniwersiteti.",
  cerrahpasa:"Istanbul Üniwersiteti, Jerrahpaşa.",
  izteknik:"Izmir Ýokary Tehnik Institudy.",
  karabuk:"Karabük Üniwersiteti.",
  koc:"Koç Üniwersiteti.",
  manisa:"Manisa Jelal B. Üniwersiteti.",
  necmettin:"Nejmeddin E. Üniwersiteti.",
  odt:"Orta Dogu Tehnik Üniwersiteti.",
  ozyegin:"Özýegin Üniwersiteti.",
  sabanci:"Sabanjy Üniwersiteti.",
  sakarya:"Sakarýa Üniwersiteti.",
  seljuk:"Seljuk Üniwersiteti.",
  tobb:"TOBB E. ve T. Üniwersiteti.",
  yildiz:"Yyldyz tehnik Üniwersiteti.",
  sb:"Saglyk Bilimler Üniwersiteti.",
  kocatepe:"Afvon Kojatepe Üniwersiteti",
  menderes:"Adnan Menderes Üniwersiteti",
  burdur:"Burdur Mehmet A. E. Üniwersiteti",
  dumlupinar:"Dumlupinar Üniwersiteti",
  binali:"Erzinjan Binali Ýyldyrym Üniwersiteti",
  eskisehir:"Eskişehir Osmangazi Üniwersiteti",
  estechnik:"Eskişehir Tehnik Üniwersiteti",
  gaziantep:"Gaziantep Üniwersiteti",
  hitit:"Hitit Üniwersiteti",
  inonu:"Inönü Üniwersiteti",
  izekonomi:"Izmir Ekonomi Üniwersiteti",
  katechnik:"Karadeniz Tehnik Üniwersiteti",
  kastomonu:"Kastomonu Üniwersiteti",
  kirikkale:"Kyrykkale Üniwersiteti",
  ahi:"Kyrşehir Ahi Ewran Üniwersiteti",
  kojaeli:"Kojaeli Üniwersiteti",
  kteknik:"Konya Tehnik Üniwersiteti",
  marmara:"Marmara Üniwersiteti",
  mersin:"Mersin Üniwersiteti",
  mus:"Muş Alp-Arslan Üniwersiteti",
  mugla:"Mugla Sykty Kochman Üniwersiteti",
  nigde:"Nigde O. H.  Üniwersiteti",
  ondokuz:"Ondokuz Mayis Üniwersiteti",
  ordu:"Ordu Üniwersiteti",
  pamukkale:"Pamukkale Üniwersiteti",
  rejep:"Rejep Taýyp Erdogan Üniwersiteti",
  scumhuriyet:"Sivas Cumhuriyet Üniwersiteti",
  suleyman:"Süleýman Demirel Üniwersiteti",
  tokat:"Tokat Gaziosmanpaşa Üniwersiteti",
  trakya:"Trakýa Üniwersiteti",
  usak:"Uşak Üniwersiteti",
  van:"Wan yuzunji yyl Üniwersiteti",
  yeditepe:"Ýeditepe Üniwersiteti",
  zonguldak:"Zonguldak B. E. Üniwersiteti",
  AlpArslan:"Adana Alp-Arslan T. Üniwersiteti",
  abdullah:"Abdullah Gül Üniwersiteti",
  adiyaman:"Adyýaman Üniwersiteti",
  agri:"Agri I. Ç. Üniwersiteti",
  keykubat:"Alanya Aladdin K. Üniwersiteti",
  amasya:"Amasya Üniwersiteti",
  asosyal:"Ankara Sosyal Bilimler Üniwersiteti",
  ardahan:"Ardahan Üniwersiteti",
  artvin:"Artwin Çoruh Üniwersiteti",
  alanya:"Alanýa H. E. Paşa Üniwersiteti",
  anka:"Anka Tehnologiýa Üniwersiteti",
  avrasya:"Awrasya Üniwersiteti",
  abilim:"Ankara Bilim Üniwersiteti",
  balikesir:"Balykesir Üniwersiteti",
  bandirmaonyedieylul:"Bandyrma Onyedi Eylül Üniwersiteti",
  bayburt:"Bayburt Üniwersiteti",
  bingol:"Bingöl Üniwersiteti",
  biruni:"Biruni Üniwersiteti",
  beren:"Bitlis Eren Üniwersiteti",
  beykent:"Beykent Üniwersiteti",
  beykoz:"Beykoz Üniwersiteti",
  con:"Çanakkale Onsekiz Mart Üniwersiteti",
  cag:"Çag Üniwersiteti",
  dumlupinar:"Dumlupinar Üniwersiteti",
  dogus:"Doguş Üniwersiteti",
  etechnik:"Erzurum Tehnik Üniwersiteti",
  fenerbahche:"Fenerbahçe Üniwersiteti",
  fsm:"Fatih Soltan M. Vakyf Üniwersiteti",
  galata:"Galatasaraý Üniwersiteti",
  giresun:"Giresun Üniwersiteti",
  gumushhane:"Gümüşhane Üniwersiteti",
  hakkari:"Hakkari Üniwersiteti",
  hatay:"Hatay Mustafa Kemal Üniwersiteti",
  halic:"Haliç Üniwersiteti",
  hkalyoncu:"Hasan Kalyonju Üniwersiteti",
  igdir:"Ygdyr Üniwersiteti",
  isik:"Yşyk Üniwersiteti",
  iteknikz:"Iskenderun Tehnik Üniwersiteti",
  arel:"Istanbul Arel Üniwersiteti",
  atlas:"Istanbul Atlas Üniwersiteti",
  Iesenyurt:"Istanbul Esenýurt Üniwersiteti",
  gedik:"Istanbul Gedik Üniwersiteti",
  kent:"Istanbul Kent Üniwersiteti",
  nisantasi:"Istanbul Nişantaşy Üniwersiteti",
  ayvansaray:"Istanbul Aywansaray Üniwersiteti",
  topkapi:"Istanbul Topkapy Üniwersiteti",
  yeniyuzyil:"Istanbul Yeni Yüzýyl Üniwersiteti",
  okan:"Istanbul Okan Üniwersiteti",
  rumeli:"Istanbul Rumeli Üniwersiteti",
  zaim:"Istanbul S. Zaim Üniwersiteti",
  sehir:"Istanbul Şehir Üniwersiteti",
  ticaret:"Istanbul Tijaret Üniwersiteti",
  itinaztepe:"Izmir Tynaztepe Üniwersiteti",
  bakircay:"Izmir Bakirçaý Üniwersiteti",
  idemokrasy:"Izmir Demokrasy Üniwersiteti",
  ikc:"Izmir K. C. Üniwersiteti",
  kafkas:"Kawkaz Üniwersiteti",
  ksi:"Kahramanmaraş S. I. Üniwersiteti",
  km:"Karamanoglu M. Üniwersiteti",
  kyrklareli:"Kyrklareli Üniwersiteti",
  kilis:"Kilis 7 Aralik Üniwersiteti",
  ksaglikbilimler:"Kütahya Saglyk Bilimler Üniwersiteti",
  gidatarim:"Gyda ve Tarym Üniwersiteti",
  lokmanhekim:"Lokman Hekim Üniwersiteti",
  mto:"Malatya T. O. Üniwersiteti",
  msguzelsanatlar:"Mimar S. Güzel Sanatlar Üniwersiteti",
  millisavunma:"Milli Sawunma Üniwersiteti",
  maltepe:"Maltepe Üniwersiteti",
  mef:"Mef Üniwersiteti",
  nhbv:"Newşehir H. B. Weli Üniwersiteti",
  okorkutata:"Osmaniýe Korkut Ata Üniwersiteti",
  pirireis:"Piri Reis Üniwersiteti",
  polakademy:"Polisiýa  Akademiýasy",
  uygulamalibilimler:"Sakarya Uýgulamali Bilimler  Üniwersiteti",
  siirt:"Siirt  Üniwersiteti",
  sinop:"Sinop  Üniwersiteti",
  sanko:"Sanko Üniwersiteti",
  tnamikkemal:"Tekirdag N. K.  Üniwersiteti",
  trabzon:"Trabzon  Üniwersiteti",
  tarsus:"Tarsus Üniwersiteti",
  tg:"Türkiye-German Üniwersiteti",
  thk:"Türkiye Hava Kurumu Üniwersiteti",
  tedu:"TED Üniwersiteti",
  shirnak:"Şirnak  Üniwersiteti",
  ufuk:"Ufuk Üniwersiteti",
  uskudar:"Üsküdar Üniwersiteti",
  yalova:"Ýalowa  Üniwersiteti",
  highihtisas:"Yüksek İhtisas Üniwersiteti",




   //KIMLIK
   aboutmainTextO:"Talyp kimligi",
   aboutmainTextI:"Işçi kimligi",
   aboutmainTextK:"Gysga wagtlyk kimlik",
   aboutKim:"Barada",
   aboutKimlikHow:"KIMLIK NÄHILI ALYNÝAR?",
   aboutVizaHow:"VIZA NÄHILI ALYNÝAR?",
   doc:"Kimlik almak ücin gerek dokumentlar:",
   docv:"Viza almak ücin gerek dokumentlar:" ,

   //dannyyKnopka
   contact:"Biziň bilen habarlaş",
   chooseP:"Haýyş birini saýlaň",
   studyA:"Okuw üçin",   
   transkript:"Transkripti ýükläň",
   grades:"Otestaty ýükläň",

  }
};

const switcher = document.getElementById("langs");
const currentLang = localStorage.getItem("lang") || "en";

// ✅ Предотврати ошибку, если язык не существует
if (!translations[currentLang]) {
  localStorage.setItem("lang", "en");
}

switcher.value = currentLang;
applyLanguage(currentLang);

switcher.addEventListener("change", () => {
  const lang = switcher.value;
  if (!translations[lang]) return;
  localStorage.setItem("lang", lang);
  applyLanguage(lang);
});

function applyLanguage(lang) {
  if (!translations[lang]) return; // 🔐 Безопасность

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    const translation = translations[lang][key];
    if (translation) {
      el.textContent = translation;
    }
  });
}

//dannyyknopka
document.addEventListener("DOMContentLoaded", function () {
  const select = document.getElementById("select");
  const form = document.getElementById("forma");

  const allInputs = Array.from(document.querySelectorAll("#form input, #form textarea, #form button, label"))
    .filter(el => el.id !== "select" && el.name !== "typeOfApply");

  // Все input type="file"
  const fileInputs = allInputs.filter(el =>
    el.tagName === "INPUT" && el.type === "file"
  );

  // Лейблы для файлов
  const transcriptLabel = document.getElementById("fileL1");
  const gradesLabel = document.getElementById("fileL2");
  const pLabel=document.getElementById('fileL3');
  function updateFormDisplay() {
    const value = select.value;

    if (value === "Bellenmedik") {
      // Скрыть всё
      allInputs.forEach(el => el.style.display = "none");
      form.style.position = "relative";
      form.style.bottom = "50vh";
    } else if (value === "Okuw") {
      // Показать всё
      allInputs.forEach(el => el.style.display = "");
      form.style.position = "relative";
      form.style.bottom = "0";
    } else if (value === "Okuwçy kimlik" || value === "Isçi kimlik") {
      // Показать всё кроме файлов и лейблов transcript + grades
      allInputs.forEach(el => el.style.display = "");

      fileInputs.forEach(el => el.style.display = "none");

      if (transcriptLabel) transcriptLabel.style.display = "none";
      if (gradesLabel) gradesLabel.style.display = "none";
      if (pLabel) pLabel.style.display = "none";
      form.style.position = "relative";
      form.style.bottom = "0";
    } else {
      // По умолчанию — показать всё
      allInputs.forEach(el => el.style.display = "");
      form.style.position = "relative";
      form.style.bottom = "0";
    }
  }

  select.addEventListener("change", updateFormDisplay);

  updateFormDisplay();
});

 //dropdown

    const dropdown=document.getElementById('dropdown');
    const content=document.getElementById('content');
    const dropdownv=document.getElementById('dropdownv');
    const contentv=document.getElementById('contentv');

    
  if (window.innerWidth <= 1000) {
      dropdown.onclick=function () {
        if (content.style.display === "flex") {
              content.style.display = "none";
            

        }else if(contentv.style.display==="flex"){
          contentv.style.display = "none";
          content.style.display="flex"
        }
       else {
              content.style.display = "flex";
        }
  } }

  

if (window.innerWidth <= 1000) {
    dropdownv.onclick=function () {
      if (contentv.style.display === "flex") {
            contentv.style.display = "none";
      }else if(content.style.display==="flex"){
        content.style.display = "none";
        contentv.style.display="flex"
      }
       else {
            contentv.style.display = "flex";
      }
} }






    const dropdownv2 = document.getElementById('dropdownv2');
  const contentv2 = document.getElementById('contentv2');
  
  dropdownv2.onclick = function () {
      if (contentv2.style.display === "flex") {
            contentv2.style.display = "none";
      } else {
            contentv2.style.display = "flex";
      }
    };
    

    const dropdown2 = document.getElementById('dropdown2');
const content2 = document.getElementById('content2');

dropdown2.onclick = function () {
    if (content2.style.display === "flex") {
          content2.style.display = "none";
    } else {
          content2.style.display = "flex";
    }
  };
    